### ISSUE TITLE
raise Type Error

### ISSUE THREAD

**Issue by Iqun1314** [mbrossar/RINS-W#1]
Dear Martin,

First thanks for your great work.

I ran the code, but there is an error I don't know how to deal with.

The error is :

raise TypeError('Invalid number of arguments passed to legend. '
TypeError: Invalid number of arguments passed to legend. Please specify either 0 args, 2 args (artist handles, figure labels) or 3 args (artist handles, figure labels, legend location)

Could you help me , thank you very much!

I'm looking forward to your reply.

**Comment by mbrossar** [comment]
I think you have to update your matplotlib Python package. The code was tested with matplotlib 2.2.3

**Comment by Iqun1314** [comment]
Thank you so much!
